### ISSUE TITLE
questions/clarification about actions/test-transfer/entrypoint.sh

### ISSUE THREAD

**Issue by omac777** [greatest-ape/aquatic#67]
After examining entrypoint.sh,
I understand it is used for testing aquatic via docker image you create and run.
In your entrypoint.sh you're installing some debian based packages and particularly rtorrent and mktorrent.
You create public cert, private key, tls.toml, udp.toml, ws.toml and launch their respective http, udp and ws aquatic trackers.

Where I start losing comprehension is the seed, leech and torrents directories and associated setup there.
You created these directories then created some test content files in seed directory:  tls-test-ipv4,  udp-test-ipv4, wss-test-ipv4.  These threw me off because they don't have any extensions.  It would have been preferred to have .txt extensions to denote these as test content files intended to make a torrent file from.

Then you proceeded to make the torrent files for these.  I'll go through the different arguments here.  The '-p' means private, not DTH nor PeerExchange. The '-o' means the destination output torrent file. The '-a' means the announced tracker url.  The last argument is the source content to share and make a torrent out of.  The source content may be a directory or a file.  In this case you chose 3 different files for the three different http/udp/ws trackers.
```
mktorrent -p -o "torrents/tls-ipv4.torrent" -a "https://example.com:3001/announce" "seed/tls-test-ipv4"
mktorrent -p -o "torrents/udp-ipv4.torrent" -a "udp://127.0.0.1:3000" "seed/udp-test-ipv4"
mktorrent -p -o "torrents/wss-ipv4.torrent" -a "wss://example.com:3002" "seed/wss-test-ipv4"
```

My first question:  The fog I have happens in the following steps.  You copy the torrents directory into different seed/leech directories.  Why?
```
cp -r torrents torrents-seed
cp -r torrents torrents-leech
```
I'm going to guess: seed is for the trackers, and leech is for the torrent clients?

My second question:  You redirected content twice to the same file: "~/.rtorrent.rc".
Why didn't you redirect that content to two different files?
For example:
```
~/.seeding_rtorrent_clients.rc
~/.leeching_rtorrent_clients.rc
```

I believe some of the above could have been documented within the usage in the README.txt to help lift the fog for aquatic beginners because I only saw how to compile it and not how to use it within the README.txt.  By placing it there, you will help more people get up to speed with this more quickly.  Thank you in advance.

**Comment by greatest-ape** [comment]
I think something that I could add to the README is what you do after you launch the tracker. If you’re running aquatic_udp on port 3000 on a server that domain example.com resolves to, people can add udp://example.com:3000 as a tracker URL to their torrent files.

As for the test, it
- setups self-signed TLS cert for example.com and makes system believe the domain points to localhost
- launches the  trackers with the cert
- creates torrent files that give example.com as tracker url
- Launches seeding clients
- Launches leeching clients
- checks that leeching clients downloaded files from seeding clients

> My first question: The fog I have happens in the following steps. You copy the torrents directory into different seed/leech directories. Why?

It’s because rtorrent makes modifications to  the directory. We want to keep seeding and leeching clients separate, and an easy way to accomplish that is to use separate directories.

> My second question: You redirected content twice to the same file: "~/.rtorrent.rc".
Why didn't you redirect that content to two different files?

I think it was just easier like that. Rtorrent loads config file on startup, as far as I know it does not reload it when it is modified.

**Comment by greatest-ape** [comment]
I’m closing this issue now. If you have more questions, you can reopen it if you’d like.
